CREATE TABLE Model ("id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, "Marka" Varchar(20), "Model" Varchar(20), "BrProdatih" INTEGER, "BrNabavljenih" INTEGER, "Profit" INTEGER)
CREATE TABLE Automobil ("id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, "RegBr" Varchar(15), "IdM" Integer, FOREIGN KEY ("IdM") REFERENCES "Model"("id") ON DELETE CASCADE)
CREATE TABLE Kupac ("id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, "ime" Varchar(10), "prezime" Varchar(20), "brLk" INTEGER, "brKupljenih" INTEGER)

CREATE TABLE "Dobavljac" ("id" INTEGER PRIMARY KEY, "Naziv" Varchar(20), "BrDobavljenih" INTEGER)
CREATE TABLE "Nabavka" ("IdA" INTEGER PRIMARY KEY, "DatumVreme" date, "IdD" INTEGER, "Cena" INTEGER, FOREIGN KEY ("IdA") REFERENCES "Automobil"("id") ON DELETE CASCADE, FOREIGN KEY ("IdD") REFERENCES "Dobavljac"("id") ON DELETE CASCADE)
CREATE TABLE "Kupovina" ("IdA" INTEGER PRIMARY KEY, "IdK" INTEGER, "DatumVreme" date, "Cena" INTEGER, FOREIGN KEY ("IdK") REFERENCES "Kupac"("Id") ON DELETE CASCADE, FOREIGN KEY ("IdA") REFERENCES "Automobil"("id") ON DELETE CASCADE)
